networks:
  default:
    driver: bridge
    name: roboshop

services:
  mongodb:
    image: praneeth2701/mongodb:v1
    container_name: mongodb
  catalogue:
    image: praneeth2701/catalogue:v1
    container_name: catalogue
    environment:
      MONGO: "true"
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on: 
    - mongodb
  redis:
    image: praneeth2701/redis:v1
    container_name: redis
  user:
    image: praneeth2701/user:v1
    container_name: user
    environment:
      MONGO: "true" 
      REDIS_URL: "redis://redis:6379" 
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on: 
    - redis
    - mongodb

